///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ranorexDocCheckCSharp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ranorexDocCheckCSharpRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c98d9b1c-bf36-4063-acdd-8e2254995b78")]
    public partial class ranorexDocCheckCSharpRepository : RepoGenBaseFolder
    {
        static ranorexDocCheckCSharpRepository instance = new ranorexDocCheckCSharpRepository();
        ranorexDocCheckCSharpRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        ranorexDocCheckCSharpRepositoryFolders.TrialActivationRanorexTestAutomatiAppFolder _trialactivationranorextestautomati;

        /// <summary>
        /// Gets the singleton class instance representing the ranorexDocCheckCSharpRepository element repository.
        /// </summary>
        [RepositoryFolder("c98d9b1c-bf36-4063-acdd-8e2254995b78")]
        public static ranorexDocCheckCSharpRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ranorexDocCheckCSharpRepository() 
            : base("ranorexDocCheckCSharpRepository", "/", null, 0, false, "c98d9b1c-bf36-4063-acdd-8e2254995b78", ".\\RepositoryImages\\ranorexDocCheckCSharpRepositoryc98d9b1c.rximgres")
        {
            _applicationundertest = new ranorexDocCheckCSharpRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _trialactivationranorextestautomati = new ranorexDocCheckCSharpRepositoryFolders.TrialActivationRanorexTestAutomatiAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c98d9b1c-bf36-4063-acdd-8e2254995b78")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("844b3a0d-4094-44e3-8e1c-4fd5cb8555fd")]
        public virtual ranorexDocCheckCSharpRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The TrialActivationRanorexTestAutomati folder.
        /// </summary>
        [RepositoryFolder("55c5270a-84a9-42cd-99a7-f3b90600ae49")]
        public virtual ranorexDocCheckCSharpRepositoryFolders.TrialActivationRanorexTestAutomatiAppFolder TrialActivationRanorexTestAutomati
        {
            get { return _trialactivationranorextestautomati; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ranorexDocCheckCSharpRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("844b3a0d-4094-44e3-8e1c-4fd5cb8555fd")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            ranorexDocCheckCSharpRepositoryFolders.SomeUlTagFolder _someultag;
            RepoItemInfo _welcometosquashtfcomponentsdocumentInfo;
            RepoItemInfo _squashtfjavajunitrunnerInfo;
            RepoItemInfo _squashtfjavajunitrunner1Info;
            RepoItemInfo _tfparamserviceInfo;
            RepoItemInfo _orgsquashtesttagalaxiatfparamservicInfo;
            RepoItemInfo _tfparamservice1Info;
            RepoItemInfo _squashtfcucumberjavarunnerInfo;
            RepoItemInfo _squashtfcucumberjavarunner1Info;
            RepoItemInfo _runnersoptionspomInfo;
            RepoItemInfo _runnersoptionspom1Info;
            RepoItemInfo _httpreposquashtestorgmaven2releasInfo;
            RepoItemInfo _squashtfexecutionserverInfo;
            RepoItemInfo _squashtfexecutionserver1Info;
            RepoItemInfo _squashtfrunnersInfo;
            RepoItemInfo _maven350Info;
            RepoItemInfo _java18Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='squash-tf.readthedocs.io']", parentFolder, 30000, null, false, "844b3a0d-4094-44e3-8e1c-4fd5cb8555fd", "")
            {
                _someultag = new ranorexDocCheckCSharpRepositoryFolders.SomeUlTagFolder(this);
                _welcometosquashtfcomponentsdocumentInfo = new RepoItemInfo(this, "WelcomeToSquashTFComponentsDocument", ".//div[#'welcome-to-squash-tf-components-documentation']/h1[@innertext>'Welcome to Squash TF components']", "", 30000, null, "a797c8b6-4cd9-4ddb-82a6-8b26b61538ca");
                _squashtfjavajunitrunnerInfo = new RepoItemInfo(this, "SquashTFJavaJunitRunner", ".//div[#'runners']//a[@innertext>'Squash TF Java Junit Runn']", "", 30000, null, "5299b317-524d-44f3-8903-0e62b14f6d5b");
                _squashtfjavajunitrunner1Info = new RepoItemInfo(this, "SquashTFJavaJunitRunner1", ".//div[#'squash-tf-java-junit-runner']/h1[@innertext>'Squash TF Java Junit Runn']", "", 30000, null, "0fd2a820-3ef7-4354-b3fc-1893d4a2319a");
                _tfparamserviceInfo = new RepoItemInfo(this, "TFParamService", ".//nav//ul/li[5]/a[@innertext='TF Param Service']", "", 30000, null, "1c7319fc-8024-482a-9513-7422adaf776e");
                _orgsquashtesttagalaxiatfparamservicInfo = new RepoItemInfo(this, "OrgSquashtestTaGalaxiatfParamServic", ".//div[#'configuration']/blockquote//pre[@innertext>'org.squashtest.ta.galaxia']", "", 30000, null, "acbc1438-39b4-4d42-b6f9-a1a7f67a0b95");
                _tfparamservice1Info = new RepoItemInfo(this, "TFParamService1", ".//div[#'tf-param-service']/h1[@innertext='TF Param Service']", "", 30000, null, "6ad4492e-ddf3-4ca4-90cb-37acecacb388");
                _squashtfcucumberjavarunnerInfo = new RepoItemInfo(this, "SquashTFCucumberJavaRunner", ".//div[#'runners']//a[@innertext>'Squash TF Cucumber Java R']", "", 30000, null, "10031dd4-e5aa-4671-98f9-734f6426971c");
                _squashtfcucumberjavarunner1Info = new RepoItemInfo(this, "SquashTFCucumberJavaRunner1", ".//div[#'squash-tf-cucumber-java-runner']/h1[@innertext>'Squash TF Cucumber Java R']", "", 30000, null, "5e9adc22-22e3-4d57-ab2b-5928ab056efa");
                _runnersoptionspomInfo = new RepoItemInfo(this, "RunnersOptionsPOM", ".//nav//ul/li[5]/a[@innertext='Runner’s options (POM)']", "", 30000, null, "d76c31d1-3e76-44e5-ab86-393298d51af0");
                _runnersoptionspom1Info = new RepoItemInfo(this, "RunnersOptionsPOM1", ".//div[#'runner-s-options-pom']/h1[@innertext='Runner’s options (POM)']", "", 30000, null, "6ce069f1-39a0-4d13-b19a-c1f4ef93f535");
                _httpreposquashtestorgmaven2releasInfo = new RepoItemInfo(this, "HttpRepoSquashtestOrgMaven2Releas", ".//div[#'runner-s-version']/?/?/a[@innertext>'http://repo.squashtest.or']", "", 30000, null, "82dbada6-f606-45cf-8971-d42752c79ec1");
                _squashtfexecutionserverInfo = new RepoItemInfo(this, "SquashTFExecutionServer", ".//div[#'squash-tf-execution-server']/h1[@innertext>'Squash TF Execution Serve']", "", 30000, null, "80ecdb2d-33ad-4e7f-9f48-377e09bb2e37");
                _squashtfexecutionserver1Info = new RepoItemInfo(this, "SquashTFExecutionServer1", ".//div[#'squash-tf-execution-server']/?/?/ul/?/?/a[@innertext>'Squash TF Execution Serve']", "", 30000, null, "2275d982-f406-49ef-b63a-866052e9bb1e");
                _squashtfrunnersInfo = new RepoItemInfo(this, "SquashTFRunners", ".//div[#'squash-tf-runners']/h1[@innertext='Squash TF Runners']", "", 30000, null, "548ca678-7391-4098-b5ef-950b87f3c1b6");
                _maven350Info = new RepoItemInfo(this, "Maven350", ".//div[#'environment-configuration']/ul[1]/li[@innertext='maven: 3.5.0']", "", 30000, null, "1ebfa685-ce97-4f8f-878e-adcc50ffea35");
                _java18Info = new RepoItemInfo(this, "Java18", ".//div[#'environment-configuration']/ul[1]/li[@innertext='java: 1.8']", "", 30000, null, "b5317db5-00d1-484d-b3a9-8c697445d792");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("844b3a0d-4094-44e3-8e1c-4fd5cb8555fd")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("844b3a0d-4094-44e3-8e1c-4fd5cb8555fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WelcomeToSquashTFComponentsDocument item.
            /// </summary>
            [RepositoryItem("a797c8b6-4cd9-4ddb-82a6-8b26b61538ca")]
            public virtual Ranorex.H1Tag WelcomeToSquashTFComponentsDocument
            {
                get
                {
                    return _welcometosquashtfcomponentsdocumentInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The WelcomeToSquashTFComponentsDocument item info.
            /// </summary>
            [RepositoryItemInfo("a797c8b6-4cd9-4ddb-82a6-8b26b61538ca")]
            public virtual RepoItemInfo WelcomeToSquashTFComponentsDocumentInfo
            {
                get
                {
                    return _welcometosquashtfcomponentsdocumentInfo;
                }
            }

            /// <summary>
            /// The SquashTFJavaJunitRunner item.
            /// </summary>
            [RepositoryItem("5299b317-524d-44f3-8903-0e62b14f6d5b")]
            public virtual Ranorex.ATag SquashTFJavaJunitRunner
            {
                get
                {
                    return _squashtfjavajunitrunnerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SquashTFJavaJunitRunner item info.
            /// </summary>
            [RepositoryItemInfo("5299b317-524d-44f3-8903-0e62b14f6d5b")]
            public virtual RepoItemInfo SquashTFJavaJunitRunnerInfo
            {
                get
                {
                    return _squashtfjavajunitrunnerInfo;
                }
            }

            /// <summary>
            /// The SquashTFJavaJunitRunner1 item.
            /// </summary>
            [RepositoryItem("0fd2a820-3ef7-4354-b3fc-1893d4a2319a")]
            public virtual Ranorex.H1Tag SquashTFJavaJunitRunner1
            {
                get
                {
                    return _squashtfjavajunitrunner1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SquashTFJavaJunitRunner1 item info.
            /// </summary>
            [RepositoryItemInfo("0fd2a820-3ef7-4354-b3fc-1893d4a2319a")]
            public virtual RepoItemInfo SquashTFJavaJunitRunner1Info
            {
                get
                {
                    return _squashtfjavajunitrunner1Info;
                }
            }

            /// <summary>
            /// The TFParamService item.
            /// </summary>
            [RepositoryItem("1c7319fc-8024-482a-9513-7422adaf776e")]
            public virtual Ranorex.ATag TFParamService
            {
                get
                {
                    return _tfparamserviceInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TFParamService item info.
            /// </summary>
            [RepositoryItemInfo("1c7319fc-8024-482a-9513-7422adaf776e")]
            public virtual RepoItemInfo TFParamServiceInfo
            {
                get
                {
                    return _tfparamserviceInfo;
                }
            }

            /// <summary>
            /// The OrgSquashtestTaGalaxiatfParamServic item.
            /// </summary>
            [RepositoryItem("acbc1438-39b4-4d42-b6f9-a1a7f67a0b95")]
            public virtual Ranorex.PreTag OrgSquashtestTaGalaxiatfParamServic
            {
                get
                {
                    return _orgsquashtesttagalaxiatfparamservicInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The OrgSquashtestTaGalaxiatfParamServic item info.
            /// </summary>
            [RepositoryItemInfo("acbc1438-39b4-4d42-b6f9-a1a7f67a0b95")]
            public virtual RepoItemInfo OrgSquashtestTaGalaxiatfParamServicInfo
            {
                get
                {
                    return _orgsquashtesttagalaxiatfparamservicInfo;
                }
            }

            /// <summary>
            /// The TFParamService1 item.
            /// </summary>
            [RepositoryItem("6ad4492e-ddf3-4ca4-90cb-37acecacb388")]
            public virtual Ranorex.H1Tag TFParamService1
            {
                get
                {
                    return _tfparamservice1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The TFParamService1 item info.
            /// </summary>
            [RepositoryItemInfo("6ad4492e-ddf3-4ca4-90cb-37acecacb388")]
            public virtual RepoItemInfo TFParamService1Info
            {
                get
                {
                    return _tfparamservice1Info;
                }
            }

            /// <summary>
            /// The SquashTFCucumberJavaRunner item.
            /// </summary>
            [RepositoryItem("10031dd4-e5aa-4671-98f9-734f6426971c")]
            public virtual Ranorex.ATag SquashTFCucumberJavaRunner
            {
                get
                {
                    return _squashtfcucumberjavarunnerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SquashTFCucumberJavaRunner item info.
            /// </summary>
            [RepositoryItemInfo("10031dd4-e5aa-4671-98f9-734f6426971c")]
            public virtual RepoItemInfo SquashTFCucumberJavaRunnerInfo
            {
                get
                {
                    return _squashtfcucumberjavarunnerInfo;
                }
            }

            /// <summary>
            /// The SquashTFCucumberJavaRunner1 item.
            /// </summary>
            [RepositoryItem("5e9adc22-22e3-4d57-ab2b-5928ab056efa")]
            public virtual Ranorex.H1Tag SquashTFCucumberJavaRunner1
            {
                get
                {
                    return _squashtfcucumberjavarunner1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SquashTFCucumberJavaRunner1 item info.
            /// </summary>
            [RepositoryItemInfo("5e9adc22-22e3-4d57-ab2b-5928ab056efa")]
            public virtual RepoItemInfo SquashTFCucumberJavaRunner1Info
            {
                get
                {
                    return _squashtfcucumberjavarunner1Info;
                }
            }

            /// <summary>
            /// The RunnersOptionsPOM item.
            /// </summary>
            [RepositoryItem("d76c31d1-3e76-44e5-ab86-393298d51af0")]
            public virtual Ranorex.ATag RunnersOptionsPOM
            {
                get
                {
                    return _runnersoptionspomInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RunnersOptionsPOM item info.
            /// </summary>
            [RepositoryItemInfo("d76c31d1-3e76-44e5-ab86-393298d51af0")]
            public virtual RepoItemInfo RunnersOptionsPOMInfo
            {
                get
                {
                    return _runnersoptionspomInfo;
                }
            }

            /// <summary>
            /// The RunnersOptionsPOM1 item.
            /// </summary>
            [RepositoryItem("6ce069f1-39a0-4d13-b19a-c1f4ef93f535")]
            public virtual Ranorex.H1Tag RunnersOptionsPOM1
            {
                get
                {
                    return _runnersoptionspom1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The RunnersOptionsPOM1 item info.
            /// </summary>
            [RepositoryItemInfo("6ce069f1-39a0-4d13-b19a-c1f4ef93f535")]
            public virtual RepoItemInfo RunnersOptionsPOM1Info
            {
                get
                {
                    return _runnersoptionspom1Info;
                }
            }

            /// <summary>
            /// The HttpRepoSquashtestOrgMaven2Releas item.
            /// </summary>
            [RepositoryItem("82dbada6-f606-45cf-8971-d42752c79ec1")]
            public virtual Ranorex.ATag HttpRepoSquashtestOrgMaven2Releas
            {
                get
                {
                    return _httpreposquashtestorgmaven2releasInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpRepoSquashtestOrgMaven2Releas item info.
            /// </summary>
            [RepositoryItemInfo("82dbada6-f606-45cf-8971-d42752c79ec1")]
            public virtual RepoItemInfo HttpRepoSquashtestOrgMaven2ReleasInfo
            {
                get
                {
                    return _httpreposquashtestorgmaven2releasInfo;
                }
            }

            /// <summary>
            /// The SquashTFExecutionServer item.
            /// </summary>
            [RepositoryItem("80ecdb2d-33ad-4e7f-9f48-377e09bb2e37")]
            public virtual Ranorex.H1Tag SquashTFExecutionServer
            {
                get
                {
                    return _squashtfexecutionserverInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SquashTFExecutionServer item info.
            /// </summary>
            [RepositoryItemInfo("80ecdb2d-33ad-4e7f-9f48-377e09bb2e37")]
            public virtual RepoItemInfo SquashTFExecutionServerInfo
            {
                get
                {
                    return _squashtfexecutionserverInfo;
                }
            }

            /// <summary>
            /// The SquashTFExecutionServer1 item.
            /// </summary>
            [RepositoryItem("2275d982-f406-49ef-b63a-866052e9bb1e")]
            public virtual Ranorex.ATag SquashTFExecutionServer1
            {
                get
                {
                    return _squashtfexecutionserver1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SquashTFExecutionServer1 item info.
            /// </summary>
            [RepositoryItemInfo("2275d982-f406-49ef-b63a-866052e9bb1e")]
            public virtual RepoItemInfo SquashTFExecutionServer1Info
            {
                get
                {
                    return _squashtfexecutionserver1Info;
                }
            }

            /// <summary>
            /// The SquashTFRunners item.
            /// </summary>
            [RepositoryItem("548ca678-7391-4098-b5ef-950b87f3c1b6")]
            public virtual Ranorex.H1Tag SquashTFRunners
            {
                get
                {
                    return _squashtfrunnersInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SquashTFRunners item info.
            /// </summary>
            [RepositoryItemInfo("548ca678-7391-4098-b5ef-950b87f3c1b6")]
            public virtual RepoItemInfo SquashTFRunnersInfo
            {
                get
                {
                    return _squashtfrunnersInfo;
                }
            }

            /// <summary>
            /// The Maven350 item.
            /// </summary>
            [RepositoryItem("1ebfa685-ce97-4f8f-878e-adcc50ffea35")]
            public virtual Ranorex.LiTag Maven350
            {
                get
                {
                    return _maven350Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Maven350 item info.
            /// </summary>
            [RepositoryItemInfo("1ebfa685-ce97-4f8f-878e-adcc50ffea35")]
            public virtual RepoItemInfo Maven350Info
            {
                get
                {
                    return _maven350Info;
                }
            }

            /// <summary>
            /// The Java18 item.
            /// </summary>
            [RepositoryItem("b5317db5-00d1-484d-b3a9-8c697445d792")]
            public virtual Ranorex.LiTag Java18
            {
                get
                {
                    return _java18Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Java18 item info.
            /// </summary>
            [RepositoryItemInfo("b5317db5-00d1-484d-b3a9-8c697445d792")]
            public virtual RepoItemInfo Java18Info
            {
                get
                {
                    return _java18Info;
                }
            }

            /// <summary>
            /// The SomeUlTag folder.
            /// </summary>
            [RepositoryFolder("b7a64a6f-e1d0-4339-ba47-4b92b53db6ea")]
            public virtual ranorexDocCheckCSharpRepositoryFolders.SomeUlTagFolder SomeUlTag
            {
                get { return _someultag; }
            }
        }

        /// <summary>
        /// The SomeUlTagFolder folder.
        /// </summary>
        [RepositoryFolder("b7a64a6f-e1d0-4339-ba47-4b92b53db6ea")]
        public partial class SomeUlTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _administrationInfo;
            RepoItemInfo _executionserverInfo;
            RepoItemInfo _usageInfo;
            RepoItemInfo _downloadInfo;
            RepoItemInfo _runnersInfo;

            /// <summary>
            /// Creates a new SomeUlTag  folder.
            /// </summary>
            public SomeUlTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeUlTag", ".//nav//ul", parentFolder, 30000, null, false, "b7a64a6f-e1d0-4339-ba47-4b92b53db6ea", "")
            {
                _administrationInfo = new RepoItemInfo(this, "Administration", "li[2]/a[@innertext='Administration']", "", 30000, null, "a96dd306-7d9d-410c-a933-1e71475095e7");
                _executionserverInfo = new RepoItemInfo(this, "ExecutionServer", "li[2]/a[@innertext='Execution Server']", "", 30000, null, "5988670b-034a-4345-9591-7708c2c8965c");
                _usageInfo = new RepoItemInfo(this, "Usage", "li[3]/a[@innertext='Usage']", "", 30000, null, "b5b4c146-077a-4f67-bc2c-a6cf79662ec1");
                _downloadInfo = new RepoItemInfo(this, "Download", "li[5]/a[@innertext='Download']", "", 30000, null, "50f6fde9-b6ee-4a69-89c5-54eccb946ccc");
                _runnersInfo = new RepoItemInfo(this, "Runners", "li[3]/a[@innertext='Runners']", "", 30000, null, "2e1ac6f3-441f-4859-97c6-896b974b66ae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7a64a6f-e1d0-4339-ba47-4b92b53db6ea")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7a64a6f-e1d0-4339-ba47-4b92b53db6ea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Administration item.
            /// </summary>
            [RepositoryItem("a96dd306-7d9d-410c-a933-1e71475095e7")]
            public virtual Ranorex.ATag Administration
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Administration item info.
            /// </summary>
            [RepositoryItemInfo("a96dd306-7d9d-410c-a933-1e71475095e7")]
            public virtual RepoItemInfo AdministrationInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The ExecutionServer item.
            /// </summary>
            [RepositoryItem("5988670b-034a-4345-9591-7708c2c8965c")]
            public virtual Ranorex.ATag ExecutionServer
            {
                get
                {
                    return _executionserverInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ExecutionServer item info.
            /// </summary>
            [RepositoryItemInfo("5988670b-034a-4345-9591-7708c2c8965c")]
            public virtual RepoItemInfo ExecutionServerInfo
            {
                get
                {
                    return _executionserverInfo;
                }
            }

            /// <summary>
            /// The Usage item.
            /// </summary>
            [RepositoryItem("b5b4c146-077a-4f67-bc2c-a6cf79662ec1")]
            public virtual Ranorex.ATag Usage
            {
                get
                {
                    return _usageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Usage item info.
            /// </summary>
            [RepositoryItemInfo("b5b4c146-077a-4f67-bc2c-a6cf79662ec1")]
            public virtual RepoItemInfo UsageInfo
            {
                get
                {
                    return _usageInfo;
                }
            }

            /// <summary>
            /// The Download item.
            /// </summary>
            [RepositoryItem("50f6fde9-b6ee-4a69-89c5-54eccb946ccc")]
            public virtual Ranorex.ATag Download
            {
                get
                {
                    return _downloadInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Download item info.
            /// </summary>
            [RepositoryItemInfo("50f6fde9-b6ee-4a69-89c5-54eccb946ccc")]
            public virtual RepoItemInfo DownloadInfo
            {
                get
                {
                    return _downloadInfo;
                }
            }

            /// <summary>
            /// The Runners item.
            /// </summary>
            [RepositoryItem("2e1ac6f3-441f-4859-97c6-896b974b66ae")]
            public virtual Ranorex.ATag Runners
            {
                get
                {
                    return _runnersInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Runners item info.
            /// </summary>
            [RepositoryItemInfo("2e1ac6f3-441f-4859-97c6-896b974b66ae")]
            public virtual RepoItemInfo RunnersInfo
            {
                get
                {
                    return _runnersInfo;
                }
            }
        }

        /// <summary>
        /// The TrialActivationRanorexTestAutomatiAppFolder folder.
        /// </summary>
        [RepositoryFolder("55c5270a-84a9-42cd-99a7-f3b90600ae49")]
        public partial class TrialActivationRanorexTestAutomatiAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TrialActivationRanorexTestAutomati  folder.
            /// </summary>
            public TrialActivationRanorexTestAutomatiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TrialActivationRanorexTestAutomati", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "55c5270a-84a9-42cd-99a7-f3b90600ae49", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55c5270a-84a9-42cd-99a7-f3b90600ae49")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55c5270a-84a9-42cd-99a7-f3b90600ae49")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
