///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckVersion recording.
    /// </summary>
    [TestModule("37d948bd-e079-4e3a-9203-69a47cbf7552", ModuleType.Recording, 1)]
    public partial class CheckVersion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static CheckVersion instance = new CheckVersion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckVersion()
        {
            java = "null";
            maven = "null";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckVersion Instance
        {
            get { return instance; }
        }

#region Variables

        string _java;

        /// <summary>
        /// Gets or sets the value of variable java.
        /// </summary>
        [TestVariable("76632744-857d-4254-9e5f-dda4150bfa60")]
        public string java
        {
            get { return _java; }
            set { _java = value; }
        }

        string _maven;

        /// <summary>
        /// Gets or sets the value of variable maven.
        /// </summary>
        [TestVariable("9cdfea8c-8f94-48e2-b90d-1bb2004f25db")]
        public string maven
        {
            get { return _maven; }
            set { _maven = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SquashTFRunners'.", repo.ApplicationUnderTest.SquashTFRunnersInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFRunnersInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Runners') on item 'ApplicationUnderTest.SquashTFRunners'.", repo.ApplicationUnderTest.SquashTFRunnersInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFRunnersInfo, "InnerText", "Squash TF Runners");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.SquashTFRunners'.", repo.ApplicationUnderTest.SquashTFRunnersInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFRunnersInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$maven) on item 'ApplicationUnderTest.Maven350'.", repo.ApplicationUnderTest.Maven350Info, new RecordItemIndex(3));
            Validate.AttributeContains(repo.ApplicationUnderTest.Maven350Info, "InnerText", maven);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.Java18'.", repo.ApplicationUnderTest.Java18Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Java18Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$java) on item 'ApplicationUnderTest.Java18'.", repo.ApplicationUnderTest.Java18Info, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ApplicationUnderTest.Java18Info, "InnerText", java);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
