///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckMvnRepoLink recording.
    /// </summary>
    [TestModule("8ee3067e-4026-41fb-9e1d-a76c47d74e42", ModuleType.Recording, 1)]
    public partial class CheckMvnRepoLink : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static CheckMvnRepoLink instance = new CheckMvnRepoLink();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckMvnRepoLink()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckMvnRepoLink Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.RunnersOptionsPOM1'.", repo.ApplicationUnderTest.RunnersOptionsPOM1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOM1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Runner’s options (POM)') on item 'ApplicationUnderTest.RunnersOptionsPOM1'.", repo.ApplicationUnderTest.RunnersOptionsPOM1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOM1Info, "InnerText", "Runner’s options (POM)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.RunnersOptionsPOM1'.", repo.ApplicationUnderTest.RunnersOptionsPOM1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOM1Info, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='http://repo.squashtest.org/maven2/release/org/squashtest/ta/galaxia/squash-tf-cucumber/') on item 'ApplicationUnderTest.HttpRepoSquashtestOrgMaven2Releas'.", repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, "InnerText", "http://repo.squashtest.org/maven2/release/org/squashtest/ta/galaxia/squash-tf-cucumber/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.HttpRepoSquashtestOrgMaven2Releas'.", repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://repo.squashtest.org/maven2/release/org/squashtest/ta/galaxia/squash-tf-cucumber/') on item 'ApplicationUnderTest.HttpRepoSquashtestOrgMaven2Releas'.", repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpRepoSquashtestOrgMaven2ReleasInfo, "Href", "http://repo.squashtest.org/maven2/release/org/squashtest/ta/galaxia/squash-tf-cucumber/");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
