///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckTFParamDependency recording.
    /// </summary>
    [TestModule("66650ba8-ca3e-4f68-ba36-e3d276d29b8c", ModuleType.Recording, 1)]
    public partial class CheckTFParamDependency : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static CheckTFParamDependency instance = new CheckTFParamDependency();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckTFParamDependency()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckTFParamDependency Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.TFParamService1'.", repo.ApplicationUnderTest.TFParamService1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamService1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='TF Param Service') on item 'ApplicationUnderTest.TFParamService1'.", repo.ApplicationUnderTest.TFParamService1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamService1Info, "InnerText", "TF Param Service");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.TFParamService1'.", repo.ApplicationUnderTest.TFParamService1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamService1Info, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='org.squashtest.ta.galaxiatf-param-service1.0.0-RELEASE') on item 'ApplicationUnderTest.OrgSquashtestTaGalaxiatfParamServic'.", repo.ApplicationUnderTest.OrgSquashtestTaGalaxiatfParamServicInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OrgSquashtestTaGalaxiatfParamServicInfo, "InnerText", "org.squashtest.ta.galaxiatf-param-service1.0.0-RELEASE");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
