///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToServerDoc recording.
    /// </summary>
    [TestModule("297e39ab-f4a9-4768-99b1-70562dd2f5ad", ModuleType.Recording, 1)]
    public partial class GoToServerDoc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static GoToServerDoc instance = new GoToServerDoc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToServerDoc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToServerDoc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome to Squash TF components documentation!') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "InnerText", "Welcome to Squash TF components documentation!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SomeUlTag.ExecutionServer'.", repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Execution Server') on item 'ApplicationUnderTest.SomeUlTag.ExecutionServer'.", repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, "InnerText", "Execution Server");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.SomeUlTag.ExecutionServer'.", repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeUlTag.ExecutionServer' at 52;12.", repo.ApplicationUnderTest.SomeUlTag.ExecutionServerInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SomeUlTag.ExecutionServer.Click("52;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Execution Server') on item 'ApplicationUnderTest.SquashTFExecutionServer'.", repo.ApplicationUnderTest.SquashTFExecutionServerInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServerInfo, "InnerText", "Squash TF Execution Server");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.SquashTFExecutionServer'.", repo.ApplicationUnderTest.SquashTFExecutionServerInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServerInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SquashTFExecutionServer1'.", repo.ApplicationUnderTest.SquashTFExecutionServer1Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServer1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Execution Server') on item 'ApplicationUnderTest.SquashTFExecutionServer1'.", repo.ApplicationUnderTest.SquashTFExecutionServer1Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServer1Info, "InnerText", "Squash TF Execution Server");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.SquashTFExecutionServer1'.", repo.ApplicationUnderTest.SquashTFExecutionServer1Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServer1Info, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://squash-tf.readthedocs.io/projects/execution-server/') on item 'ApplicationUnderTest.SquashTFExecutionServer1'.", repo.ApplicationUnderTest.SquashTFExecutionServer1Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFExecutionServer1Info, "Href", "https://squash-tf.readthedocs.io/projects/execution-server/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SquashTFExecutionServer1' at 92;1.", repo.ApplicationUnderTest.SquashTFExecutionServer1Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.SquashTFExecutionServer1.Click("92;1");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
