///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToTFParamDoc recording.
    /// </summary>
    [TestModule("f1189827-7d71-4aac-a0ae-0588dcd2ce22", ModuleType.Recording, 1)]
    public partial class GoToTFParamDoc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static GoToTFParamDoc instance = new GoToTFParamDoc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToTFParamDoc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToTFParamDoc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Java Junit Runner') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner1'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunner1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunner1Info, "InnerText", "Squash TF Java Junit Runner");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner1'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunner1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunner1Info, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='TF Param Service') on item 'ApplicationUnderTest.TFParamService'.", repo.ApplicationUnderTest.TFParamServiceInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamServiceInfo, "InnerText", "TF Param Service");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.TFParamService'.", repo.ApplicationUnderTest.TFParamServiceInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamServiceInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://squash-tf.readthedocs.io/projects/runner-java-junit/en/doc-stable/tf-param-service.html') on item 'ApplicationUnderTest.TFParamService'.", repo.ApplicationUnderTest.TFParamServiceInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TFParamServiceInfo, "Href", "https://squash-tf.readthedocs.io/projects/runner-java-junit/en/doc-stable/tf-param-service.html");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TFParamService' at 132;16.", repo.ApplicationUnderTest.TFParamServiceInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TFParamService.Click("132;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
