///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToRunners recording.
    /// </summary>
    [TestModule("ce3b2c95-d2dd-47ea-8795-3666f14eefbb", ModuleType.Recording, 1)]
    public partial class GoToRunners : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static GoToRunners instance = new GoToRunners();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToRunners()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToRunners Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome to Squash TF components documentation!') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "InnerText", "Welcome to Squash TF components documentation!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SomeUlTag.Runners'.", repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Runners') on item 'ApplicationUnderTest.SomeUlTag.Runners'.", repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, "InnerText", "Runners");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.SomeUlTag.Runners'.", repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://squash-tf.readthedocs.io/en/latest/runner/overview.html') on item 'ApplicationUnderTest.SomeUlTag.Runners'.", repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, "Href", "https://squash-tf.readthedocs.io/en/latest/runner/overview.html");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeUlTag.Runners' at 63;13.", repo.ApplicationUnderTest.SomeUlTag.RunnersInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.SomeUlTag.Runners.Click("63;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
