///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToRunnerOptions recording.
    /// </summary>
    [TestModule("e501e845-fc5e-43fc-81a6-44b9c135f1fa", ModuleType.Recording, 1)]
    public partial class GoToRunnerOptions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static GoToRunnerOptions instance = new GoToRunnerOptions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToRunnerOptions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToRunnerOptions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SquashTFCucumberJavaRunner1'.", repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Cucumber Java Runner') on item 'ApplicationUnderTest.SquashTFCucumberJavaRunner1'.", repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, "InnerText", "Squash TF Cucumber Java Runner");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.SquashTFCucumberJavaRunner1'.", repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFCucumberJavaRunner1Info, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.RunnersOptionsPOM'.", repo.ApplicationUnderTest.RunnersOptionsPOMInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOMInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Runner’s options (POM)') on item 'ApplicationUnderTest.RunnersOptionsPOM'.", repo.ApplicationUnderTest.RunnersOptionsPOMInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOMInfo, "InnerText", "Runner’s options (POM)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.RunnersOptionsPOM'.", repo.ApplicationUnderTest.RunnersOptionsPOMInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOMInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://squash-tf.readthedocs.io/projects/runner-cucumber-java/en/doc-stable/usage.html#runner-s-options-pom') on item 'ApplicationUnderTest.RunnersOptionsPOM'.", repo.ApplicationUnderTest.RunnersOptionsPOMInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RunnersOptionsPOMInfo, "Href", "https://squash-tf.readthedocs.io/projects/runner-cucumber-java/en/doc-stable/usage.html#runner-s-options-pom");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RunnersOptionsPOM' at 140;12.", repo.ApplicationUnderTest.RunnersOptionsPOMInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RunnersOptionsPOM.Click("140;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
