///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ranorexDocCheckCSharp.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToJUnitRunnerDoc recording.
    /// </summary>
    [TestModule("e90c227a-7baa-49ec-9248-a0918b70d3cc", ModuleType.Recording, 1)]
    public partial class GoToJUnitRunnerDoc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repository.
        /// </summary>
        public static global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository repo = global::ranorexDocCheckCSharp.ranorexDocCheckCSharpRepository.Instance;

        static GoToJUnitRunnerDoc instance = new GoToJUnitRunnerDoc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToJUnitRunnerDoc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToJUnitRunnerDoc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome to Squash TF components documentation!') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "InnerText", "Welcome to Squash TF components documentation!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'ApplicationUnderTest.WelcomeToSquashTFComponentsDocument'.", repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.WelcomeToSquashTFComponentsDocumentInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Squash TF Java Junit Runner') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, "InnerText", "Squash TF Java Junit Runner");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='a') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, "TagName", "a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://squash-tf.readthedocs.io/projects/runner-java-junit') on item 'ApplicationUnderTest.SquashTFJavaJunitRunner'.", repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, "Href", "https://squash-tf.readthedocs.io/projects/runner-java-junit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SquashTFJavaJunitRunner' at 71;7.", repo.ApplicationUnderTest.SquashTFJavaJunitRunnerInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SquashTFJavaJunitRunner.Click("71;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
